{% set python_min = "3.9" %}
{% set name = "ccflow" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86f14c4052fde88420aa00c033aaf5942d15a1cb3a1891277b30d8ce54b622e6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cloudpathlib
    - cloudpickle
    - dask
    - hydra-core
    - ipython
    - jinja2
    - narwhals
    - numpy <3
    - orjson
    - pandas
    - pyarrow
    - pydantic >=2.6,<3
    - smart_open
    - tenacity

test:
  imports:
    - ccflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/point72/ccflow
  summary: 'ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection'
  description: |
    ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ptomecek
    - timkpaine
