{% set python_min = "3.9" %}
{% set name = "ccflow" %}
{% set version = "0.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/67/78/219300b544d3889cea642549dd1170b0cb0c53d58afe15e3dcd0ddd3bd7e/ccflow-{{ version }}.tar.gz
  sha256: 667d433035b3a5659bccc21a4b9fc6bad61b1b05dbcb9836d5f59ea611a40bbb

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cloudpathlib
    - cloudpickle
    - dask
    - hydra-core
    - ipython
    - jinja2
    - narwhals
    - numpy <3
    - orjson
    - pandas
    - pyarrow
    - pydantic >=2.6,<3
    - smart_open
    - tenacity

test:
  imports:
    - ccflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/point72/ccflow
  summary: 'ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection'
  description: |
    ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ptomecek
    - timkpaine
