{% set name = "ccflow" %}
{% set version = "0.9.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fc/f9/6d6cdeb2e1e3f1df5c2f27ac4576e744c2dc84806d1eff8dc51cfcdec6a1/ccflow-{{ version }}.tar.gz
  sha256: 455b6f6659f4231c6eb145ec5ba74cff3d1e59046ab926eb713983ee1c1ca876

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cloudpathlib
    - cloudpickle
    - dask
    - deprecated
    - hydra-core
    - ipython
    - jinja2
    - narwhals
    - numpy <3
    - orjson
    - pandas
    - pyarrow
    - pydantic >=2.6,<3
    - smart_open
    - tenacity

test:
  imports:
    - ccflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/point72/ccflow
  summary: 'ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection'
  description: |
    ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ptomecek
    - timkpaine
