{% set name = "ccflow" %}
{% set version = "0.8.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/52/c2/b2169d80b1792eca1f2cfc698e89c536d2cd63909a6e7cc34c992be3029a/ccflow-{{ version }}.tar.gz
  sha256: 48977de7bfef83a254495b62be513c9de8d8599cec94d1945eca4694637f7ed1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cloudpathlib
    - cloudpickle
    - dask
    - deprecated
    - hydra-core
    - ipython
    - jinja2
    - narwhals
    - numpy <3
    - orjson
    - pandas
    - pyarrow
    - pydantic >=2.6,<3
    - smart_open
    - tenacity

test:
  imports:
    - ccflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/point72/ccflow
  summary: 'ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection'
  description: |
    ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ptomecek
    - timkpaine
